/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as BecomeOwnerRouteImport } from './routes/become-owner'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApartmentsRouteImport } from './routes/apartments'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApartmentsIdRouteImport } from './routes/apartments.$id'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeOwnerRoute = BecomeOwnerRouteImport.update({
  id: '/become-owner',
  path: '/become-owner',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApartmentsRoute = ApartmentsRouteImport.update({
  id: '/apartments',
  path: '/apartments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApartmentsIdRoute = ApartmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApartmentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apartments': typeof ApartmentsRouteWithChildren
  '/auth': typeof AuthRoute
  '/become-owner': typeof BecomeOwnerRoute
  '/my-bookings': typeof MyBookingsRoute
  '/owner': typeof OwnerRoute
  '/planning': typeof PlanningRoute
  '/profile': typeof ProfileRoute
  '/apartments/$id': typeof ApartmentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apartments': typeof ApartmentsRouteWithChildren
  '/auth': typeof AuthRoute
  '/become-owner': typeof BecomeOwnerRoute
  '/my-bookings': typeof MyBookingsRoute
  '/owner': typeof OwnerRoute
  '/planning': typeof PlanningRoute
  '/profile': typeof ProfileRoute
  '/apartments/$id': typeof ApartmentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apartments': typeof ApartmentsRouteWithChildren
  '/auth': typeof AuthRoute
  '/become-owner': typeof BecomeOwnerRoute
  '/my-bookings': typeof MyBookingsRoute
  '/owner': typeof OwnerRoute
  '/planning': typeof PlanningRoute
  '/profile': typeof ProfileRoute
  '/apartments/$id': typeof ApartmentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apartments'
    | '/auth'
    | '/become-owner'
    | '/my-bookings'
    | '/owner'
    | '/planning'
    | '/profile'
    | '/apartments/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apartments'
    | '/auth'
    | '/become-owner'
    | '/my-bookings'
    | '/owner'
    | '/planning'
    | '/profile'
    | '/apartments/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apartments'
    | '/auth'
    | '/become-owner'
    | '/my-bookings'
    | '/owner'
    | '/planning'
    | '/profile'
    | '/apartments/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApartmentsRoute: typeof ApartmentsRouteWithChildren
  AuthRoute: typeof AuthRoute
  BecomeOwnerRoute: typeof BecomeOwnerRoute
  MyBookingsRoute: typeof MyBookingsRoute
  OwnerRoute: typeof OwnerRoute
  PlanningRoute: typeof PlanningRoute
  ProfileRoute: typeof ProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-owner': {
      id: '/become-owner'
      path: '/become-owner'
      fullPath: '/become-owner'
      preLoaderRoute: typeof BecomeOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apartments': {
      id: '/apartments'
      path: '/apartments'
      fullPath: '/apartments'
      preLoaderRoute: typeof ApartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apartments/$id': {
      id: '/apartments/$id'
      path: '/$id'
      fullPath: '/apartments/$id'
      preLoaderRoute: typeof ApartmentsIdRouteImport
      parentRoute: typeof ApartmentsRoute
    }
  }
}

interface ApartmentsRouteChildren {
  ApartmentsIdRoute: typeof ApartmentsIdRoute
}

const ApartmentsRouteChildren: ApartmentsRouteChildren = {
  ApartmentsIdRoute: ApartmentsIdRoute,
}

const ApartmentsRouteWithChildren = ApartmentsRoute._addFileChildren(
  ApartmentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApartmentsRoute: ApartmentsRouteWithChildren,
  AuthRoute: AuthRoute,
  BecomeOwnerRoute: BecomeOwnerRoute,
  MyBookingsRoute: MyBookingsRoute,
  OwnerRoute: OwnerRoute,
  PlanningRoute: PlanningRoute,
  ProfileRoute: ProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
