/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApartmentsRouteImport } from './routes/apartments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApartmentsIdRouteImport } from './routes/apartments.$id'

const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApartmentsRoute = ApartmentsRouteImport.update({
  id: '/apartments',
  path: '/apartments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApartmentsIdRoute = ApartmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApartmentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apartments': typeof ApartmentsRouteWithChildren
  '/auth': typeof AuthRoute
  '/my-bookings': typeof MyBookingsRoute
  '/owner': typeof OwnerRoute
  '/apartments/$id': typeof ApartmentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apartments': typeof ApartmentsRouteWithChildren
  '/auth': typeof AuthRoute
  '/my-bookings': typeof MyBookingsRoute
  '/owner': typeof OwnerRoute
  '/apartments/$id': typeof ApartmentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apartments': typeof ApartmentsRouteWithChildren
  '/auth': typeof AuthRoute
  '/my-bookings': typeof MyBookingsRoute
  '/owner': typeof OwnerRoute
  '/apartments/$id': typeof ApartmentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apartments'
    | '/auth'
    | '/my-bookings'
    | '/owner'
    | '/apartments/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apartments'
    | '/auth'
    | '/my-bookings'
    | '/owner'
    | '/apartments/$id'
  id:
    | '__root__'
    | '/'
    | '/apartments'
    | '/auth'
    | '/my-bookings'
    | '/owner'
    | '/apartments/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApartmentsRoute: typeof ApartmentsRouteWithChildren
  AuthRoute: typeof AuthRoute
  MyBookingsRoute: typeof MyBookingsRoute
  OwnerRoute: typeof OwnerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apartments': {
      id: '/apartments'
      path: '/apartments'
      fullPath: '/apartments'
      preLoaderRoute: typeof ApartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apartments/$id': {
      id: '/apartments/$id'
      path: '/$id'
      fullPath: '/apartments/$id'
      preLoaderRoute: typeof ApartmentsIdRouteImport
      parentRoute: typeof ApartmentsRoute
    }
  }
}

interface ApartmentsRouteChildren {
  ApartmentsIdRoute: typeof ApartmentsIdRoute
}

const ApartmentsRouteChildren: ApartmentsRouteChildren = {
  ApartmentsIdRoute: ApartmentsIdRoute,
}

const ApartmentsRouteWithChildren = ApartmentsRoute._addFileChildren(
  ApartmentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApartmentsRoute: ApartmentsRouteWithChildren,
  AuthRoute: AuthRoute,
  MyBookingsRoute: MyBookingsRoute,
  OwnerRoute: OwnerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
